app/routes.php
<?php
Route::controller('tweets', 'TweetsController');
Route::controller('signups', 'SignupsController');
Route::controller('login', 'LoginController');
Route::controller('admin', 'AdminController');
Route::controller('create', 'CreateController');

//Scorecard CRUD routes
Route::get('create/scorecard', array('as' => 'createscorecard', 'uses' => 'CreateController@getScorecard'));
Route::post('create/scorecard', array('as' => 'createscorecard', 'uses' => 'CreateController@postScorecard'));
Route::get('deletescorecard/{id}', 'DeleteController@deleteScorecard');
Route::get('updatescorecard/{id}', array('as' => 'updatescorecard', 'uses' => 'UpdateController@getScorecard'));
Route::post('updatescorecard/{id}', array('as' => 'postscorecardupdate', 'uses' => 'UpdateController@postScorecard'));
Route::post('reorder/scorecards', array('as' => 'updatescorecardorder', 'uses' => 'UpdateController@updateScorecardOrder'));

//FAQ CRUD routes
Route::post('create/faq', array('as' => 'createFAQ', 'use' => 'CreateController@postFaq'));
Route::get('create/faq', array('as' => 'createFAQ', 'use' => 'CreateController@getFaq'));
Route::post('updatefaq/{id}', array('as' => 'postupdatefaq', 'uses' => 'UpdateController@postFaq'));
Route::get('updatefaq/{id}', array('as' => 'updatefaq', 'uses' => 'UpdateController@getFaq'));
Route::post('reorder/faqs', array('as' => 'updatefaqorder', 'uses' => 'UpdateController@updateFaqOrder'));
Route::get('deletefaq/{id}', 'DeleteController@deleteFaq');

Route::get('delete/{id}', 'DeleteController@deletePost');
Route::get('deletestate/{id}', 'DeleteController@deleteState');

Route::any('update/{id}', 'UpdateController@updatePost');
Route::any('updatestate/{id}', 'UpdateController@updateState');


Route::get('news/{slug}', 'NewsController@showNews');

Route::get('privacy-policy', function()
{
	return View::make('pages.privacy')
							->with('current_page', 'privacy-policy');
});

Route::get('logout', function()
{
	Auth::logout();
	return Redirect::to('login')->with('message', 'You have been successfully logged out!');
});

Route::get('/indexold', 'HomeController@getIndexOld');
Route::post('/indexold', 'HomeController@postIndexOld');

Route::get('/', 'HomeController@getIndex');
Route::post('/', 'HomeController@postIndex');

Route::get('/social', 'SocialController@getIndex');

Route::get('/scorecard', 'ScorecardController@getIndex');

Route::get('/frequently-asked-questions', 'FaqsController@getIndex');
Route::get('/faqs', 'FaqsController@getIndex');
Route::get('/FAQ', 'FaqsController@getIndex');


Route::get('/{stateurl}', 'StatesController@showState');

Route::get('widget/template', function () {
	$buttons = array(
		array(
			'label' => 'Read More',
			'url' => 'http://donttaxtheinter.net'
		),
		array(
			'label' => 'Tweet #NoNetTax',
			'url' => 'https://twitter.com/intent/tweet?text=' . urlencode("Don't let Congress pass an Internet sales tax that could cost your family $360! Tell them: No! http://bit.ly/1ywmEzh #NoNetTax")
		)
	);
	$button = $buttons[array_rand($buttons)];
	$backgroundNo = mt_rand(1, 2);

	$widgetStat = new WidgetStat;
	$widgetStat->user_id = (Input::has('userId') && Input::get('userId') != 'null') ? Input::get('userId') : Session::getId();
	$widgetStat->session_id = (Input::has('sessionId') && Input::get('sessionId') != 'null') ? Input::get('sessionId') : Session::getId();
	$widgetStat->url = Input::get('url');
	$widgetStat->user_agent = Request::server('HTTP_USER_AGENT');
	$widgetStat->ip_address = Request::server('REMOTE_ADDR');
	$widgetStat->background_no = $backgroundNo;
	$widgetStat->button_label = $button['label'];
	$widgetStat->button_url = $button['url'];
	$widgetStat->widget_size = (Input::has('size') && Input::get('size') != 'null') ? strtoupper(Input::get('size')) : 'SMALL';
	$widgetStat->clicks = 0;
	$widgetStat->save();

	$response = Response::json(array(
		'background' => 'background' . $backgroundNo,
		'button' => $button,
		'session_id' => $widgetStat->session_id,
		'user_id' => $widgetStat->user_id,
	));
	$response->headers->set('Access-Control-Allow-Origin', '*');
	return $response;
});

Route::get('widget/click', function () {
	$widgetStat = WidgetStat::where('session_id', Input::get('sessionId'))->first();
	$widgetStat->clicks = $widgetStat->clicks + 1;
	$widgetStat->save();

	$response = Response::json(array('success' => true));
	$response->headers->set('Access-Control-Allow-Origin', '*');
	return $response;
});

// Set 404 page
App::missing(function ($exception) {
	if (Str::contains(Request::path(), '/')) {
		return Response::view('pages.404', array(), 404);
	} else {
		return App::make('HomeController')->getIndex();
	}
});

app/models/Signup.php
<?php

class Signup extends Eloquent {

	public function getNameAttribute($value)
    {
        return trim($this->attributes['first_name'] . ' ' . $this->attributes['last_name']);
    }
	
}

app/views/pages/admin/dashboard.blade.php
@extends('layouts.admin')

@section('content')

		<div class="dashboard-links">
			<a href="/create/quote" class="btn btn-primary btn-large"><i class="ficon-plus"></i> Add a Quote</a>
			<a href="/create/article" class="btn btn-primary btn-large"><i class="ficon-plus"></i> Add a Link</a>
			<a href="/create/subpage" class="btn btn-primary btn-large"><i class="ficon-plus"></i> Add a Subpage</a>
			<a href="/create/video" class="btn btn-primary btn-large"><i class="ficon-facetime-video"></i> Add a Video</a>
			<a href="/create/scorecard" class="btn btn-primary btn-large"><i class="ficon-group"></i> Add a Scorecard</a>
			<a href="/create/faq" class="btn btn-primary btn-large"><i class="ficon-group"></i> Add a FAQ</a>
			<a href="/signups" class="btn btn-primary btn-large"><i class="ficon-group"></i> View Signups</a>
			<a href="/admin/states" class="btn btn-primary btn-large"><i class="ficon-group"></i> States</a>
		</div>


	<div class="row">
		<div class="span12">
			<ul id="tiles">

				@foreach ($posts as $post)

					@if ($post->post_type == 'QUOTE')
						<li class="quote"><h5><span class="icon-quote"></span>Quote</h5>
							<blockquote>{{ $post->postType->text }}</blockquote>
							<p>&mdash;{{ $post->postType->author }}</p>
							<div class="edit-bar">
				     		   	<a href="/update/{{ $post->id }}"># {{ $post->order }}</a>
					        	<a href="/update/{{ $post->id }}">Edit</a>
					        	<a href="/delete/{{ $post->id }}">Delete</a>
					        </div>
						</li>
					@endif

					@if ($post->post_type == 'ARTICLE')
					<li class="news">
				        <h5><span class="icon-article-alt"></span>Link</h5>

				        @if (!empty($post->postType->image_file_name))
							<img src="/uploads/{{ $post->postType->image_file_name }}">
				        @endif

				        <h3>{{ $post->postType->title }}</h3>
				        <p><a href="{{ $post->postType->source }}">{{ $post->postType->host }} //</a> {{ $post->postType->excerpt }}</p>
				        <a href="{{ $post->postType->url }}" class="read-more">Read&raquo;</a>
				        <div class="edit-bar">
    					    <a href="/update/{{ $post->id }}"># {{ $post->order }}</a>
				        	<a href="/update/{{ $post->id }}">Edit</a>
				        	<a href="/delete/{{ $post->id }}">Delete</a>
				        </div>
			        </li>
					@endif

					@if ($post->post_type == 'SUBPAGE')
					<li class="news">
				        <h5><span class="icon-article-alt"></span>News</h5>

				        @if (!empty($post->postType->thumb_file_name))
							<img src="/uploads/{{ $post->postType->thumb_file_name }}">
				        @endif

				        <h3>{{ $post->postType->title }}</h3>
				        <p><a href="{{ $post->postType->source }}">{{ $post->postType->host }} //</a> {{ $post->postType->excerpt }}</p>
				        <a href="/news/{{ $post->postType->slug }}" class="read-more">Read&raquo;</a>
				        <div class="edit-bar">
				        	<a href="/update/{{ $post->id }}"># {{ $post->order }}</a>
				        	<a href="/update/{{ $post->id }}">Edit</a>
				        	<a href="/delete/{{ $post->id }}">Delete</a>
				        </div>
			        </li>
					@endif

					@if ($post->post_type == 'VIDEO')
					<li class="video">
				        <h5><span class="awesome-font"><i class="ficon-facetime-video"></i></span>Video</h5>


						<a rel="shadowbox" href="https://www.youtube.com/embed/{{ $post->postType->youtube_id }}?autoplay=1"><img src="{{ str_replace('http://','https://',$post->postType->thumbnail) }}"><div class="ficon-play"></div></a>

				        <h3>{{ $post->postType->title }}</h3>

				        @if (!empty($post->postType->description))
				        	<p>{{ $post->postType->description }}</p>
				        @endif

				        <div class="edit-bar">
			     		   	<a href="/update/{{ $post->id }}"># {{ $post->order }}</a>
				        	<a href="/update/{{ $post->id }}">Edit</a>
				        	<a href="/delete/{{ $post->id }}">Delete</a>
				        </div>

			        </li>
					@endif

				@endforeach

			</ul>
		</div>
	</div>

@stop

app/views/pages/admin/heat.blade.php
@extends('layouts.admin')

@section('back')
	<div class="row small-links">
		<div class="span12">
			<a href="/signups" class="btn btn-primary btn-large"><i class="ficon-arrow-left"></i> Go Back</a>
		</div>
	</div>
@stop


@section('content')
<div class="row">
	<div class="span12">
		<div id="panel">
			<button onclick="toggleHeatmap()" class="btn">Toggle Heatmap</button>
			<button onclick="changeGradient()" class="btn">Change gradient</button>
			<button onclick="changeRadius()" class="btn">Change radius</button>
			<button onclick="changeOpacity()" class="btn">Change opacity</button>
		</div>
		<h3>Showing last 25,000 signups. (All signups since {{ $min_date }} )</h3>
		<div id="map"></div>
	</div>
</div>

<script>
	var map, pointarray, heatmap;



	// $.ajax({
	// 	url 		: '/signups/map',
	// 	type 		: 'POST',
	// 	dataType 	: 'json',
	// 	success 	: function(data) {

	// 		$.each(data, function(index, location) {

	// 			if (location.lat == null) {
	// 				return;
	// 			}
	// 		});

	// 	}
	// });


	

	var signups = [
		@foreach ($signups as $signup)
			@if (!is_null($signup->lat) || !is_null($signup->lng))
	  			new google.maps.LatLng({{ $signup->lat }}, {{ $signup->lng }}),
			@endif
		@endforeach
	];

	function initialize() {
	  var mapOptions = {
	    zoom: 5,
	    center: new google.maps.LatLng(39.909736, -102.084961),
	    mapTypeId: google.maps.MapTypeId.ROADMAP
	  };

	  map = new google.maps.Map(document.getElementById('map'),
	      mapOptions);

	  var pointArray = new google.maps.MVCArray(signups);

	  heatmap = new google.maps.visualization.HeatmapLayer({
	    data: pointArray
	  });

	  heatmap.setMap(map);
	}

	function toggleHeatmap() {
	  heatmap.setMap(heatmap.getMap() ? null : map);
	}

	function changeGradient() {
	  var gradient = [
	    'rgba(0, 255, 255, 0)',
	    'rgba(0, 255, 255, 1)',
	    'rgba(0, 191, 255, 1)',
	    'rgba(0, 127, 255, 1)',
	    'rgba(0, 63, 255, 1)',
	    'rgba(0, 0, 255, 1)',
	    'rgba(0, 0, 223, 1)',
	    'rgba(0, 0, 191, 1)',
	    'rgba(0, 0, 159, 1)',
	    'rgba(0, 0, 127, 1)',
	    'rgba(63, 0, 91, 1)',
	    'rgba(127, 0, 63, 1)',
	    'rgba(191, 0, 31, 1)',
	    'rgba(255, 0, 0, 1)'
	  ]
	  heatmap.setOptions({
	    gradient: heatmap.get('gradient') ? null : gradient
	  });
	}

	function changeRadius() {
	  heatmap.setOptions({radius: heatmap.get('radius') ? null : 20});
	}

	function changeOpacity() {
	  heatmap.setOptions({opacity: heatmap.get('opacity') ? null : 0.2});
	}

	google.maps.event.addDomListener(window, 'load', initialize);
</script>



@stop

app/views/pages/admin/login.blade.php
@extends('layouts.admin')

@section('content')

	<div class="row">
			<div class="span12">
				<h2>Login</h2>
				
				{{ $errors->first('email', '<div class="alert alert-error">:message</div>') }}
				{{ $errors->first('password', '<div class="alert alert-error">:message</div>') }}

				@if (Session::has('login_error') && Session::get('login_error') === TRUE)
					<div class="alert alert-error">The logins don't match!</div>
				@endif

				{{ Form::open(array('url' => 'login', 'class' => 'form-horizontal')) }}
					<div class="control-group {{ $errors->first('email', 'error') }}">
						{{ Form::label('email', 'Email', array('class' => 'control-label')) }}
				    	<div class="controls">
							{{ Form::text('email', Input::old('email')) }}
						</div>
					</div>
					<div class="control-group {{ $errors->first('password', 'error') }}">
						{{ Form::label('password', 'Password', array('class' => 'control-label')) }}
						<div class="controls">
							{{ Form::password('password') }}
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							  <button type="submit" class="btn">Sign in</button>
						</div>
					</div>
				{{ Form::close() }}
			</div>
		</div>

@stop

app/views/pages/admin/map.blade.php
@extends('layouts.admin')

@section('back')
	<div class="row small-links">
		<div class="span12">
			<a href="/signups" class="btn btn-primary btn-large"><i class="ficon-arrow-left"></i> Go Back</a>
		</div>
	</div>
@stop


@section('content')
<div class="row">
	<div class="span12">
		<div id="map"></div>
	</div>
</div>


	

<script>
		

				var styles = [
				{
					stylers: [
					{ saturation: -85 }
					]
				},{
					featureType: 'road',
					elementType: 'geometry',
					stylers: [
					{ hue: "#002bff" },
					{ visibility: 'simplified' }
					]
				},{
					featureType: 'road',
					elementType: 'labels',
					stylers: [
					{ visibility: 'off' }
					]
				}
				];


				var map = new google.maps.Map(document.getElementById('map'), {
					zoom: 5,
					center: new google.maps.LatLng(39.909736, -102.084961),
					mapTypeId: google.maps.MapTypeId.ROADMAP
				});

				map.setOptions({styles: styles});

				var infowindow = new google.maps.InfoWindow();

				var marker, i;

				var approximate_location;

				$.ajax({
					url 		: '/signups/map',
					type 		: 'POST',
					dataType 	: 'json',
					success 	: function(data) {

						$.each(data, function(index, location) {

							if (location.lat == null) {
								return;
							}

							marker = new google.maps.Marker({
								position: new google.maps.LatLng(location.lat, location.lng),
								map: map
							});

							google.maps.event.addListener(marker, 'click', (function(marker, i) {
								return function() {

	var content = '';
	content += '<strong>ID: </strong> '+location.id+'</a>' ;
	content += '<br>';
	content += '<strong>Email: </strong> <a href="mailto:'+location.email+'">'+location.email+'</a>';
	content += '<br>';
	content += '<strong>Name: </strong>'+location.first_name+' '+location.last_name;
	content += '<br>';
	content += '<strong>Address: </strong>'+location.city+', '+location.state+', '+location.zip_code;
	content += '<br>';
	content += '<strong>Signed at: </strong>'+location.created_at;


									infowindow.setContent(content);
									infowindow.open(map, marker);
								}
							})(marker, i));
						});

					}
				});


						
		
			
		</script>

@stop

app/views/pages/admin/signups.blade.php
@extends('layouts.admin')

@section('back')
	<div class="row small-links">
		<div class="span12">
			<a href="/admin" class="btn btn-primary btn-large"><i class="ficon-arrow-left"></i> Go Back</a>
			<a href="/signups/sync" class="btn btn-primary btn-large"><i class="ficon-refresh ficon-spin"></i> Sync</a>
			<a href="/signups/map" class="btn btn-primary btn-large"><i class="ficon-map-marker"></i> Map</a>
			<a href="/signups/heat" class="btn btn-primary btn-large"><i class="ficon-fire"></i> Heat Map</a>
			<a href="/signups/vector" class="btn btn-primary btn-large"><i class="ficon-globe"></i> Density Map</a>
			<a href="/signups/download" class="btn btn-primary btn-large btn-export"><i class="ficon-save"></i> Export</a>
		</div>
	</div>
@stop

@section('content')

	<div class="row">
		<div class="span12">
			<h1 class="big-page-title" align="middle">Signups</h1>
		</div>
	</div>

	<div class="row">
		<div class="span12">
			<h2><strong>Total Signups: </strong>{{ number_format($signupsCount) }}</h2>
		</div>
	</div>

@stop

app/views/pages/admin/statelist.blade.php
@extends('layouts.admin')


@section('content')

	<div class="row">
		<div class="span12">
			<h1 class="big-page-title" align="middle">States</h1>
		
			<div class="dashboard-links">
				<a href="/create/state" class="btn btn-primary btn-large"><i class="ficon-group"></i> New State</a>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span12">
			<h2><strong>Total Count: </strong>{{ count($states) }}</h2>
			<table id="sort-me" class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Headline</th>
						<th>Subheadline</th>
						<th>URL Slug</th>
						<th>Delete</th>
						
					</tr>
				</thead>
				<tbody>
					@foreach($states as $state)
					<tr>
						<td>{{ $state->id }}</td>
						<td><a href="/updatestate/{{ $state->id }}">{{ $state->name }}</a></td>
						<td>{{ $state->headline }}</td>
						<td>{{ $state->subheadline }}</td>
						<td><a href="/{{ $state->url }}">/{{ $state->url }}</a></td>
						<td><a href="/deletestate/{{ $state->id }}">DELETE</a></td>
						
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>

@stop

app/views/pages/admin/vector.blade.php
@extends('layouts.admin')

@section('back')
	<div class="row small-links">
		<div class="span12">
			<a href="/signups" class="btn btn-primary btn-large"><i class="ficon-arrow-left"></i> Go Back</a>
		</div>
	</div>
@stop


@section('content')
<h3>Showing last 25,000 signups. (All signups since {{ $min_date }} )</h3>
<div id="map"></div>

<script>
	var density = {
		@foreach ($signups as $key => $value)
		"{{ $key }}": {{ $value }},
		@endforeach
	};

	$(function() {
		$('#map').vectorMap({
			map: 'us_aea_en',
			series: {
				regions: [{
					scale: ['#EBC7D6', '#630709'],
					attribute: 'fill',
					values: density,
					min: 0,
					max: 1586,
					normalizeFunction: 'polynomial'
				}]
			},
			onRegionLabelShow: function(event, label, code) {
				label.html(label.html()+'<br>Total Signups: '+density[code]);
			},
			backgroundColor: 'none',
			zoomOnScroll: false 
		});
	});
	
	
	</script>

	
@stop